

language: python
matrix:
  include:
      - os: linux
        python: 2.7
        env: TOXENV=py27
      - os: linux
        python: 3.5
        env: TOXENV=py35
      - os: linux
        python: 3.6
        env: TOXENV=py36
      - os: linux
        python: 3.7
        env: TOXENV=py37
install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda install -c anaconda setuptools
  - conda update --yes conda
  - pip install -r requirements_dev.txt
  - pip install -e .
script:
  - pytest --cov-report term-missing --cov=pyscal tests/

env:
  - CODECOV_TOKEN="9a576708-79d8-4899-880b-8aa1124531e1"

after_success:
  - codecov
  - test $TRAVIS_BRANCH = "master" && conda install conda-build && conda install anaconda-client && bash conda-recipe/conda_upload.sh

