#add the different platforms to test
#in case of windows the following line has to be added
#windows: 'vs2017-win2016'

variables:
  linux: 'ubuntu-16.04'
  mac: 'macos-10.13'

#do not include branches as of now
#trigger:
#- master

jobs:
- job: 'Linux'
  pool:
    vmImage: $(linux)

  strategy:
    matrix:
      Python27:
        python.version: '2.7'
      Python37:
        python.version: '3.7'
    maxParallel: 4

  steps:
    - bash: |
        echo "##vso[task.prependpath]$CONDA/bin"
        conda create --yes --quiet --name conenv
        source activate conenv
        conda config --set always_yes yes --set changeps1 no
        conda config --add channels conda-forge
        conda install -c conda-forge libiconv
        conda install -c anaconda setuptools
        conda update --yes conda
        conda install -q conda-build
      displayName: Setup Anaconda Environment

    - bash: |
        source activate conenv
        conda install -c conda-forge --file requirements_dev.txt
        pip install -e .
      displayName: Install package

    - bash: |
        source activate conenv
        pytest --cov-report term-missing --cov=pyscal tests/
        codecov
      displayName: Run tests

    - bash: |
        and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
        conda install conda-build
        conda install anaconda-client
        bash conda-recipe/conda_upload.sh
      displayName: Upload to conda
