package:
  name: pyscal
  version: "2.0.0"

source:
  git_rev: "2.0.0"
  git_url: https://github.com/srmnitc/pyscal.git
  path: ../src/

requirements:
  build:
    - python
    - setuptools
    - numpy

  run:
    - python

test:
  imports:
    - pyscal

about:
  home: https://github.com/srmnitc/pyscal
  license: GNU
  summary:

