package:
  name: pyscal
  version: {{ environ['VERSION'] }}

source:
  git_url: https://github.com/srmnitc/pyscal.git
  path: ../src/

requirements:
  build:
    - python
    - setuptools
    - numpy

  run:
    - python

build:
    script_env:
        - VERSION
        - CONDA_BLD_PATH
test:
  imports:
    - pyscal

about:
  home: https://github.com/srmnitc/pyscal
  license_file: LICENSE
  summary: "Python library written in C++ for calculation of local atomic structural environment"
  doc_url: https://pyscal.com

extra:
  recipe-maintainers:
     - srmnitc

