title: Steinhardt Tools
logo: /assets/img/logo.png
description: Python library for calculation of Steinhardt's bond order parameters.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
