channels:
  - conda-forge
dependencies:
  - pip:
    - pybind11
    - numpy
    - ase
    - h5py
    - ipywidgets==7.5
    - plotly==4.11.0
    - sphinx_rtd_theme
    - m2r2
    - furo
    - nbsphinx


